// This program will build a c file

#include<stdio.h>

void main(){
    FILE *ptr;
    ptr = fopen("print.c", "w");

    char st[50];
    printf("Enter the c code:\n");
    gets(st);

    fprintf(ptr, "// This c code is generated by c.c file\n");
    fprintf(ptr, "#include<stdio.h>\n");
    fprintf(ptr , "void main(){\n   ");

    int i=0;
    while(st[i] != '\0'){
        fputc(st[i], ptr);
        i++;
    }
    
    fprintf(ptr, "\n}");
    fclose(ptr);
}